install.packages("foreign")
install.packages("MASS")
install.packages("aod")
install.packages("ggplot2")
install.packages("pwr")
install.packages("CCA")
install.packages("CCP")
install.packages("truncreg")
